#!/bin/bash --login

#PBS -l walltime=01:00:00

#PBS -l select=1:ncpus=32

#PBS -N 2018_cr_nojoin_no_golay_series

#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

export TMPDIR=~/qiime_tmp

echo "loading virtualenv"

source activate qiime1

module load R-3.3.1-gcc-6.2.0-zjrjm3s

time compare_categories.py --method anosim -i ~/2018_02_smb/core_div_anal_Proteo_pH_final/bdiv_even11800/weighted_unifrac_dm.txt -m ~/2018_02_smb/mapping_complete_2018_filtered_notph.tsv -c SamplePh -o anosim_CC_Ph_proteo_W -n 999

source deactivate
