#!/bin/bash --login

#PBS -l walltime=01:00:00

#PBS -l select=1:ncpus=32

#PBS -N 2018_cr_nojoin_no_golay_series

#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

echo "loading virtualenv"

export TMPDIR=~/qiime_tmp

source activate qiime1

time compare_categories.py --method bioenv -i core_div_anal/bdiv_even605/unweighted_unifrac_dm.txt -m mapping_complete_2018.tsv -c SamplePh -o Bioenv_pH  

source deactivate

