#!/bin/bash --login

#PBS -l walltime=01:00:00

#PBS -l select=1:ncpus=32

#PBS -N 2018_cr_nojoin_no_golay_series

#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

echo "loading virtualenv"

export TMPDIR=~/qiime_tmp

source activate qiime1

time filter_samples_from_otu_table.py -i otus1/otu_table.biom -m mapping_complete_2018.tsv -o OTUs_Filtered_By_Sample.biom --sample_id_fp mapping_complete_2018.tsv

source deactivate 
