#!/bin/bash --login

#PBS -l walltime=01:00:00

#PBS -l select=1:ncpus=32

#PBS -N 2018_cr_nojoin_no_golay_series

#PBS -A d411-training


cd $PBS_O_WORKDIR

module load miniconda/python2

echo "loading virtualenv"

export TMPDIR=~/qiime_tmp

source activate qiime1

time group_significance.py -i ~/2018_02_smb/otus1/otu_table.biom -m ~/2018_02_smb/mapping_complete_2018.tsv -c SamplePh -o Group_Significance_pH.txt
 
source deactivate 
