#!/bin/bash --login

#PBS -l walltime=01:00:00

#PBS -l select=1:ncpus=32

#PBS -N 2018_cr_nojoin_no_golay_series

#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

echo "loading virtualenv"

export TMPDIR=~/qiime_tmp

source activate qiime1

make_otu_heatmap.py -i core_div_anal_pH_final/taxa_plots/table_mc34000_sorted_L2.biom -m mapping_complete_2018.tsv -o heatmap_complete.pdf --color_scheme gnuplot2

source deactivate

