#!/bin/bash --login

#PBS -l walltime=01:00:00

#PBS -l select=1:ncpus=32

#PBS -N 2018_cr_nojoin_no_golay_serial

#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

echo "loading virtualenv"

source activate qiime1

export TMPDIR=~/qiime_tmp

echo "splitting libraries"

time split_libraries_fastq.py -i seqprep_assembled.fastq.gz -b seqprep_assembled.fastq_barcodes.fastq -o slout -m mapping_complete_2018.tsv -q 19 --rev_comp_barcode --rev_comp_mapping_barcodes

Source deactivate
                                          
